# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpMdyOSV18OnySXZDab77neENDJOaVq-
"""

def Valores_repetidos(lst, index = 0, duplicados = set ()):
  if index >= len(lst) - 1:
    return duplicados

  elemento_actual = lst[index]

  if elemento_actual in lst[index + 1:]:
    duplicados.add(elemento_actual)


  return Valores_repetidos(lst, index + 1, duplicados)


lista = [1,2,3,4,4,5,6,7,8,1]
repetidos = Valores_repetidos(lista)
print("los valores repetidos de la lista son", repetidos )